---
title: "initial_viz"
author: "Madelyn Hair"
date: "2024-11-19"
output: html_document
---
#Testing commit to github, part 2
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
require("knitr")
opts_knit$set(root.dir = "~/Library/CloudStorage/GoogleDrive-maha7624@colorado.edu/Shared drives/Field Research Videos/Gil Lab/Projects_2024/Plastics/completed_annotations_plastics")
```

Load necessary packages
```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(readr)
library(purrr)
library(stringr)
```

Set working directory to data folder
```{r}
setwd("~/Library/CloudStorage/GoogleDrive-maha7624@colorado.edu/Shared drives/Field Research Videos/Gil Lab/Projects_2024/Plastics/completed_annotations_plastics")
#csvfiles<-dir(pattern="\\.csv")
#csvout<-lapply(csvfiles, function(file) read.csv(file))
#names(csvout) <- csvfiles

tsvfiles<-dir(pattern="\\.tsv")
tsvout<-lapply(tsvfiles, function(file) {
 suppressWarnings({
  df <-read_delim(file, delim ="\t", col_types = cols(
     #matching the variable type for PC and Mac
    `Observation date` = col_character(),
    `Modifier #1` = col_double(),
    `Start (s)` = col_double(),
    `Stop (s)` = col_double(),
    `Duration (s)` = col_double(),
    `Time offset (s)` = col_double(),
    `Coding duration` = col_double(),
    `Media duration (s)` = col_double(),
    `FPS (frame/s)` = col_double(),
    `Observation duration by subject by observation` = col_double(),
    `Image index start` = col_double(),
    `Image index stop` = col_double()
  )) 
 })
  if ("Modifiers" %in% colnames(df)) {
    df <- df %>% mutate(Modifiers = as.character(Modifiers), `Observation date`=as.character(`Observation date`), `Total length` = as.numeric(`Total length`)) %>%
      mutate(`Start (s)`= as.numeric(`Start (s)`), `Stop (s)` = as.numeric(`Stop (s)`), `Duration (s)` = as.numeric(`Duration (s)`)) %>%
      select(-FPS)
  }
 if ("Modifier #1" %in% colnames(df)) {
    df <- df %>% rename(Plot = `Modifier #1`)
  }
  return(df)
  })
names(tsvout) <- tsvfiles

#out<-append(csvout, tsvout)
out<- tsvout
```


```{r}
full.df<- bind_rows(out, .id = "column_label") %>%
  dplyr::rename(Observation = column_label) %>%
  select(-c(Description:`Media file`)) %>%
  mutate(
    Observer = sub("_.*", "", Observation),  # Extract everything before the first _
  ) %>%
   select(-c(Observation, `Behavioral category`)) %>%
  select(-one_of(intersect(c("Date", "Media files/Live observation", "Subjects"), colnames(.)))) %>%
  dplyr::rename(Start = 'Start (s)',
                Stop = 'Stop (s)') %>% 
  mutate(
    Site = word(`Observation id`, 2, sep = "_"),
    Phase = word(`Observation id`, 3, sep = "_"),
    Photoperiod = word(`Observation id`, 4, sep = "_"),
    Video_name = word(`Observation id`, 5, sep = "_"),
     Species= sub("\\d$", "", Subject)) %>%

mutate(Plot = coalesce(
    as.numeric(sapply(strsplit(as.character(Modifiers), "\\|"), `[`, 1)),
    as.numeric(Plot)
  )) %>%

   mutate(Bottles = case_when(
    Site %in% c("A03", "A05") & Plot == 1 ~ "No bottle",
    Site %in% c("A03", "A05") & Plot == 2 ~ "Biofouled bottle",
    Site %in% c("A03", "A05") & Plot == 3 ~ "Clean bottle",

    Site %in% c("A07", "A09") & Plot == 1 ~ "No bottle",
    Site %in% c("A07", "A09") & Plot == 2 ~ "Clean bottle",
    Site %in% c("A07", "A09") & Plot == 3 ~ "Biofouled bottle",

    Site %in% c("A10") & Plot == 1 ~ "Clean bottle",
    Site %in% c("A10") & Plot == 2 ~ "No bottle",
    Site %in% c("A10") & Plot == 3 ~ "Biofouled bottle",
  ),
    Bottles = factor(Bottles, levels = c("No bottle", "Biofouled bottle", "Clean bottle")),
    Phase = factor(Phase, levels=c("pre", "addition", "acclim", "removal")))


```


Visualize frequency plots
```{r}
spp_freq<-full.df%>%
  group_by(Subject,`Observation id`, Plot) %>%
  slice(1) %>% #keeps only the first observation of each subject in a video's plot for the frequency count
  ungroup() %>%
  group_by(Phase, Species, Bottles) %>%
  summarise(freq=n()) %>%
  ungroup() %>%
  filter(!is.na(Species), !is.na(Bottles))%>%
  complete(Phase, Species, Bottles) %>%
  mutate(Species=factor(Species, levels = c("Damselfish", "Grunt", "Goatfish", "Parrotfish", "Surgeonfish", "Snapper", "Wrasse","Jack", "Grouper","Butterfly", "Other", "No focal subject")), 
         Phase = factor(Phase, levels= c("pre", "addition", "acclim", "removal"))
  )

#Make na's 0 so there is a value for every species and every phase
spp_freq$freq[is.na(spp_freq$freq)] <- 0


all_visits<-ggplot(spp_freq, aes(x = Phase, y = freq, color = Bottles)) + 
  geom_point ()+
  geom_line(aes(group=Bottles))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = .5, hjust = .5))+
  facet_wrap(~Species) + 
  labs(title="Visitation Rates, All Plots")
all_visits
```

```{r}
bites_sum<-full.df %>%
  filter(Behavior=="bite")%>%
  group_by(Phase, Bottles, Site) %>%
  summarize(total_bites=n())
bitesp<- ggplot(bites_sum, aes(x = Phase, y = total_bites, color = Bottles)) +
  geom_point()+
  geom_line(aes(group=Bottles))+
  facet_wrap(~Site)
bitesp
```

```{r}
ggsave("All_visitation_0107.png", all_visits, height = 10, width = 10)
ggsave("All_Bites_0107.png", bitesp, height=5, width= 10)
```

